export const actionTypes = {
  START_FETCHING_MENU_BAKERY_ONE: 'START_FETCHING_MENU_BAKERY_ONE',
  FETCHED_MENU_BAKERY_ONE: 'FETCHED_MENU_BAKERY_ONE',
  FETCH_ERROR_MENU_BAKERY_ONE: 'FETCH_ERROR_MENU_BAKERY_ONE'
}