export const actionTypes = {

  IMAGE_VIEW: 'IMAGE_VEIW',
  IMAGE_NEXT: 'IMAGE_NEXT',
  IMAGE_PREV: 'IMAGE_PREV',

  START_FETCHING: 'START_FETCHING',
  FETCHED: 'FETCHED',
  FETCH_ERROR: 'FETCH_ERROR',

  FETCH_CATEGORY: 'FETCH_CATEGORY',
  CATEGORY_IMAGE_ID: 'CATEGORY_IMAGE_ID',
  CATEGORY_IMAGE_ID_NEXT: 'CATEGORY_IMAGE_ID_NEXT',
  CATEGORY_IMAGE_ID_PREV: 'CATEGORY_IMAGE_ID_PREV',
  CATEGORY_IMAGE_ID_CLOSE: 'CATEGORY_IMAGE_ID_CLOSE',
  FETCH_ABOUT: 'FETCH_ABOUT',



  PLAY_ALL_TRACKS: 'PLAY_ALL_TRACKS',

  PAGINATION: 'PAGINATION',
  GOTOPAGE: 'GOTOPAGE',



}