export const actionTypes = {

  START_FETCHING: 'START_FETCHING',
  FETCHED: 'FETCHED',
  FETCH_ERROR: 'FETCH_ERROR',


  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  PHOTO_GROUP_TAG_ID: 'PHOTO_GROUP_TAG_ID'

}