export const actionTypes = {

  START_FETCHING_MENU_FOUR: 'START_FETCHING_MENU_FOUR',
  FETCHED_MENU_FOUR: 'FETCHED_MENU_FOUR',
  FETCH_ERROR_MENU_FOUR: 'FETCH_ERROR_MENU_FOUR',

  START_FETCHING_USER_MENU_FOUR: 'START_FETCHING_USER_MENU_FOUR',
  FETCHED_USER_MENU_FOUR: 'FETCHED_USER_MENU_FOUR',
  FETCH_ERROR_USER_MENU_FOUR: 'FETCH_ERROR_USER_MENU_FOUR',

  DROP_MENU: 'DROP_MENU'

}