export const BlogOneActionTypes = {
  BLOG_ONE_PAGES: 'BLOG_ONE_PAGES',
  BLOG_ONE_NEXT_PAGE: 'BLOG_ONE_NEXT_PAGE',
  BLOG_ONE_PREV_PAGE: 'BLOG_ONE_PREV_PAGE',
  BLOG_ONE_BACK_TO_PAGES: 'BLOG_ONE_BACK_TO_PAGES'
}