export const actionTypes = {

  START_FETCHING_MAGAZINE_MENU: 'START_FETCHING_MAGAZINE_MENU',
  FETCHED_MAGAZINE_MENU: 'FETCHED_MAGAZINE_MENU',
  FETCH_ERROR_MAGAZINE_MENU: 'FETCH_ERROR_MAGAZINE_MENU',

  START_FETCHING_USER_MENU_FOUR: 'START_FETCHING_USER_MENU_FOUR',
  FETCHED_USER_MENU_FOUR: 'FETCHED_USER_MENU_FOUR',
  FETCH_ERROR_USER_MENU_FOUR: 'FETCH_ERROR_USER_MENU_FOUR',

  OPEN_MEGHA_MENU: 'OPEN_MEGHA_MENU',
  OPEN_SEARCH: 'OPEN_SEARCH',

}