export const actionTypes = {

  BLOG_ONE_BLOG_FETCHING: 'BLOG_ONE_BLOG_FETCHING',
  BLOG_ONE_BLOG_FETCHED: 'BLOG_ONE_BLOG_FETCHED',
  BLOG_ONE_BLOG_FETCH_ERROR: 'BLOG_ONE_BLOG_FETCH_ERROR',

  BLOG_ONE_BY_TAXONOMY_FETCHING: 'BLOG_ONE_BY_TAXONOMY_FETCHING',
  BLOG_ONE_BY_TAXONOMY_FETCHED: 'BLOG_ONE_BY_TAXONOMY_FETCHED',
  BLOG_ONE_BY_TAXONOMY_FETCH_ERROR: 'BLOG_ONE_BY_TAXONOMY_FETCH_ERROR',

}