export const actionTypes = {

  SELECT_PROJECT_GROUP_ITEM: 'SELECT_PROJECT_GROUP_ITEM',
  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  PLAY_THE_TRACK: 'PLAY_THE_TRACK',
  PAUSE_THE_TRACK: 'PAUSE_THE_TRACK',
  STOP_THE_TRACK: 'STOP_THE_TRACK',

  PAGINATION_ITEMS_IN_A_PAGE: 'PAGINATION_ITEMS_IN_A_PAGE',
  PAGINATION_ITEM_START: 'PAGINATION_ITEM_START',
  PAGINATION_ITEM_PREV: 'PAGINATION_ITEM_PREV',
  PAGINATION_ITEM_NEXT: 'PAGINATION_ITEM_NEXT',

}